[deploy]
startCommand = "python manage.py migrate && gunicorn ehcl.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
name = "django-backend"
type = "web" 