# Generated by Django 5.1.7 on 2025-05-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
