# Generated by Django 5.1.7 on 2025-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthcenter_email_healthcenter_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcenter',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='conditions_treated',
            field=models.TextField(blank=True, help_text='Comma-separated list of conditions treated', null=True),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='has_ambulance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='has_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='has_pharmacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='is_emergency',
            field=models.BooleanField(default=True, help_text='24/7 emergency services available'),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='specialties',
            field=models.TextField(blank=True, help_text='Comma-separated list of medical specialties', null=True),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='country',
            field=models.CharField(default='Uganda', max_length=255),
        ),
    ]
