# Generated by Django 5.2.1 on 2025-05-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_healthcenter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number format: +256 XXX XXXXXX (e.g., +256 752 234567)', max_length=20, null=True),
        ),
    ]
