# Generated by Django 5.2.3 on 2025-06-20 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_healthcenter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
