# Generated by Django 5.1.7 on 2025-07-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_center', 'New Health Center Nearby'), ('facility_update', 'Facility Update'), ('system', 'System Announcement'), ('account', 'Account Activity'), ('emergency', 'Emergency Alert'), ('appointment', 'Appointment Update')], max_length=50),
        ),
    ]
