# Generated by Django 5.1.7 on 2025-07-05 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='hospital_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL),
        ),
    ]
