# Generated by Django 5.1.7 on 2025-07-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_healthcenter_hospital_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number format: +256 XXX XXXXXX', max_length=20, null=True),
        ),
    ]
