# Generated by Django 5.1.7 on 2025-07-05 06:38

from django.db import migrations, models


def set_default_phone(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.filter(phone__isnull=True):
        user.phone = '+256 000 000000'  # Default placeholder phone
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_phone'),
    ]

    operations = [
        # First, set default values for existing users with null phone
        migrations.RunPython(set_default_phone, reverse_code=migrations.RunPython.noop),
        
        # Then make the field non-nullable
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Phone number format: +256 XXX XXXXXX', max_length=20),
        ),
    ]
