# Generated by Django 5.1.7 on 2025-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250705_0938'),
    ]

    operations = [
        # Remove phone field from User model
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        
        # Add phone field to Appointment model
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='+256 000 000000', help_text='Patient phone number for contact', max_length=20),
        ),
    ]
