# Generated by Django 4.2.7 on 2025-07-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20250705_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(help_text='Patient phone number for contact', max_length=20),
        ),
    ]
