export interface Hospital {
  id: string;
  name: string;
  district: string;
  description: string;
  address: string;
  coords: { latitude: number; longitude: number };
  imageUrl: string; // placeholder image URL
}

export const HOSPITALS: Hospital[] = [
  // Mbarara District (10)
  { id: 'hosp-001', name: 'Mbarara Regional Referral Hospital', district: 'Mbarara', description: 'Main government referral facility offering comprehensive services.', address: 'Bishop Wills Rd, Mbarara', coords: { latitude: -0.6075, longitude: 30.6580 }, imageUrl: 'https://via.placeholder.com/600x300?text=Mbarara+Referral' },
  { id: 'hosp-002', name: 'Mbarara Community Clinic', district: 'Mbarara', description: 'Local clinic with outpatient and maternal care.', address: 'Nyamitanga Hill, Mbarara', coords: { latitude: -0.6192, longitude: 30.6578 }, imageUrl: 'https://via.placeholder.com/600x300?text=Community+Clinic' },
  { id: 'hosp-003', name: 'St. Francis Hospital Rubaga', district: 'Mbarara', description: 'Catholic-run hospital focusing on surgery and pediatrics.', address: 'Kakiika, Mbarara', coords: { latitude: -0.6021, longitude: 30.6833 }, imageUrl: 'https://via.placeholder.com/600x300?text=St+Francis' },
  { id: 'hosp-004', name: 'Lake Mburo Health Center', district: 'Mbarara', description: 'Health center serving local communities around Lake Mburo.', address: 'Lake Mburo Rd, Mbarara', coords: { latitude: -0.8333, longitude: 30.9667 }, imageUrl: 'https://via.placeholder.com/600x300?text=Lake+Mburo+HC' },
  { id: 'hosp-005', name: 'Mbarara Women’s Hospital', district: 'Mbarara', description: 'Specialized maternity and gynecology services.', address: 'Kikagate Rd, Mbarara', coords: { latitude: -0.6060, longitude: 30.6605 }, imageUrl: 'https://via.placeholder.com/600x300?text=Women+Hospital' },
  { id: 'hosp-006', name: 'Mbarara Cancer Center', district: 'Mbarara', description: 'Oncology unit providing cancer diagnostics and treatment.', address: 'Bishop Wills Rd, Mbarara', coords: { latitude: -0.6080, longitude: 30.6590 }, imageUrl: 'https://via.placeholder.com/600x300?text=Cancer+Center' },
  { id: 'hosp-007', name: 'Mbarara Eye Care Clinic', district: 'Mbarara', description: 'Specialist clinic for ophthalmology and vision care.', address: 'Bishop Stuart Rd, Mbarara', coords: { latitude: -0.6035, longitude: 30.6568 }, imageUrl: 'https://via.placeholder.com/600x300?text=Eye+Care' },
  { id: 'hosp-008', name: 'Rubaga Dental Clinic', district: 'Mbarara', description: 'Dental services including orthodontics.', address: 'Kakiika Rd, Mbarara', coords: { latitude: -0.6100, longitude: 30.6700 }, imageUrl: 'https://via.placeholder.com/600x300?text=Dental+Clinic' },
  { id: 'hosp-009', name: 'Mbarara Pediatric Hospital', district: 'Mbarara', description: 'Child-focused inpatient and outpatient medical care.', address: 'Nyamityobora Rd, Mbarara', coords: { latitude: -0.6115, longitude: 30.6612 }, imageUrl: 'https://via.placeholder.com/600x300?text=Pediatric+Hospital' },
  { id: 'hosp-010', name: 'Mbarara Skin & Allergy Center', district: 'Mbarara', description: 'Dermatology and allergy diagnostics.', address: 'Kakyeka Rd, Mbarara', coords: { latitude: -0.6050, longitude: 30.6625 }, imageUrl: 'https://via.placeholder.com/600x300?text=Skin+Center' },

  // Lira District (10)
  { id: 'hosp-011', name: 'Lira Regional Referral Hospital', district: 'Lira', description: 'Primary referral for Northern Uganda with full acute services.', address: 'Lira–Gulu Rd, Lira', coords: { latitude: 2.2429, longitude: 32.8998 }, imageUrl: 'https://via.placeholder.com/600x300?text=Lira+Referral' },
  { id: 'hosp-012', name: 'Olive Health Clinic', district: 'Lira', description: 'Private clinic specializing in women’s health and minor surgeries.', address: 'Health Centre Rd, Lira', coords: { latitude: 2.2461, longitude: 32.9075 }, imageUrl: 'https://via.placeholder.com/600x300?text=Olive+Clinic' },
  { id: 'hosp-013', name: 'St. Charles Lwanga Hospital', district: 'Lira', description: 'Faith-based hospital with surgical and maternity wards.', address: 'Adiko Rd, Lira', coords: { latitude: 2.2500, longitude: 32.9000 }, imageUrl: 'https://via.placeholder.com/600x300?text=St+Charles' },
  { id: 'hosp-014', name: 'Lira Mother & Child Center', district: 'Lira', description: 'Dedicated maternity and pediatric services.', address: 'Dokolo Rd, Lira', coords: { latitude: 2.2450, longitude: 32.8920 }, imageUrl: 'https://via.placeholder.com/600x300?text=Mother+Child' },
  { id: 'hosp-015', name: 'Gweri Health Centre IV', district: 'Lira', description: 'Government health center with emergency care.', address: 'Gweri Town, Lira', coords: { latitude: 2.2300, longitude: 32.8800 }, imageUrl: 'https://via.placeholder.com/600x300?text=Health+Centre+IV' },
  { id: 'hosp-016', name: 'St. Monica Clinic', district: 'Lira', description: 'Outpatient clinic with lab and imaging.', address: 'Anaka Rd, Lira', coords: { latitude: 2.2550, longitude: 32.9100 }, imageUrl: 'https://via.placeholder.com/600x300?text=St+Monica' },
  { id: 'hosp-017', name: 'Lira Mental Health Unit', district: 'Lira', description: 'Psychiatric and counseling services.', address: 'Lira–Amolatar Rd, Lira', coords: { latitude: 2.2400, longitude: 32.8950 }, imageUrl: 'https://via.placeholder.com/600x300?text=Mental+Health' },
  { id: 'hosp-018', name: 'St. Mary’s Dental Clinic', district: 'Lira', description: 'Dental care and oral surgery.', address: 'Adik Rd, Lira', coords: { latitude: 2.2420, longitude: 32.9005 }, imageUrl: 'https://via.placeholder.com/600x300?text=Dental+Clinic' },
  { id: 'hosp-019', name: 'Lira Eye Center', district: 'Lira', description: 'Ophthalmology diagnostics and surgeries.', address: 'Gulu Rd, Lira', coords: { latitude: 2.2480, longitude: 32.9020 }, imageUrl: 'https://via.placeholder.com/600x300?text=Eye+Center' },
  { id: 'hosp-020', name: 'St. Joseph’s Paramedical', district: 'Lira', description: 'Paramedical support and physiotherapy.', address: 'Laropi Rd, Lira', coords: { latitude: 2.2440, longitude: 32.8985 }, imageUrl: 'https://via.placeholder.com/600x300?text=Paramedical' },

  // Jinja District (10)
  { id: 'hosp-021', name: 'Jinja Regional Referral Hospital', district: 'Jinja', description: 'Major referral offering neurology and burn care.', address: 'Busoga Rd, Jinja', coords: { latitude: 0.4409, longitude: 33.2032 }, imageUrl: 'https://via.placeholder.com/600x300?text=Jinja+Referral' },
  { id: 'hosp-022', name: 'Victoria Nile Clinic', district: 'Jinja', description: 'General outpatient services by the river.', address: 'Nile Ave, Jinja', coords: { latitude: 0.4333, longitude: 33.2035 }, imageUrl: 'https://via.placeholder.com/600x300?text=Victoria+Clinic' },
  { id: 'hosp-023', name: 'St. Benedict’s Hospital', district: 'Jinja', description: 'Faith-based facility with maternity and surgery.', address: 'Buwenge Rd, Jinja', coords: { latitude: 0.4450, longitude: 33.2090 }, imageUrl: 'https://via.placeholder.com/600x300?text=St+Benedict' },
  { id: 'hosp-024', name: 'Jinja Eye Institute', district: 'Jinja', description: 'Specialist ophthalmic center.', address: 'Mayuge Rd, Jinja', coords: { latitude: 0.4380, longitude: 33.2000 }, imageUrl: 'https://via.placeholder.com/600x300?text=Eye+Institute' },
  { id: 'hosp-025', name: 'River Side Dental Clinic', district: 'Jinja', description: 'Dental and orthodontic services.', address: 'Lugard Rd, Jinja', coords: { latitude: 0.4415, longitude: 33.2040 }, imageUrl: 'https://via.placeholder.com/600x300?text=Dental+Clinic' },
  { id: 'hosp-026', name: 'Jinja Women’s Health Center', district: 'Jinja', description: 'Gynecology and family planning services.', address: 'Njeru Rd, Jinja', coords: { latitude: 0.4300, longitude: 33.1980 }, imageUrl: 'https://via.placeholder.com/600x300?text=Women+Health' },
  { id: 'hosp-027', name: 'Jinja Pediatric Center', district: 'Jinja', description: 'Child health and immunization.', address: 'Iganga Rd, Jinja', coords: { latitude: 0.4440, longitude: 33.2060 }, imageUrl: 'https://via.placeholder.com/600x300?text=Pediatrics' },
  { id: 'hosp-028', name: 'Nile Delta Clinic', district: 'Jinja', description: 'General practice and diagnostics.', address: 'Queen Elizabeth Way, Jinja', coords: { latitude: 0.4370, longitude: 33.2020 }, imageUrl: 'https://via.placeholder.com/600x300?text=Nile+Clinic' },
  { id: 'hosp-029', name: 'St. Luke’s Paramedical', district: 'Jinja', description: 'Physiotherapy and rehabilitation.', address: 'Lugazi Rd, Jinja', coords: { latitude: 0.4420, longitude: 33.2070 }, imageUrl: 'https://via.placeholder.com/600x300?text=Rehab+Clinic' },
  { id: 'hosp-030', name: 'Jinja Skin & Allergy', district: 'Jinja', description: 'Modern dermatology services.', address: 'Mabira Rd, Jinja', coords: { latitude: 0.4390, longitude: 33.2015 }, imageUrl: 'https://via.placeholder.com/600x300?text=Dermatology' },

  // Gulu District (10)
  { id: 'hosp-031', name: 'Gulu Regional Referral Hospital', district: 'Gulu', description: 'Top referral with trauma and pediatric wards.', address: 'Gulu-Atiak Rd, Gulu', coords: { latitude: 2.7724, longitude: 32.2881 }, imageUrl: 'https://via.placeholder.com/600x300?text=Gulu+Referral' },
  { id: 'hosp-032', name: 'Mercy Family Clinic', district: 'Gulu', description: 'Comprehensive family care including dental and maternal.', address: 'Angal Rd, Gulu', coords: { latitude: 2.7795, longitude: 32.2813 }, imageUrl: 'https://via.placeholder.com/600x300?text=Mercy+Clinic' },
  { id: 'hosp-033', name: 'St. Jude’s Hospital', district: 'Gulu', description: 'Health services with a focus on surgery.', address: 'Laroo-Pece Rd, Gulu', coords: { latitude: 2.7840, longitude: 32.2940 }, imageUrl: 'https://via.placeholder.com/600x300?text=St+Jude' },
  { id: 'hosp-034', name: 'Gulu Eye Centre', district: 'Gulu', description: 'Specialized ophthalmic treatments.', address: 'Laroo-Pece Rd, Gulu', coords: { latitude: 2.7800, longitude: 32.2900 }, imageUrl: 'https://via.placeholder.com/600x300?text=Eye+Centre' },
  { id: 'hosp-035', name: 'Lacor Memorial Hospital', district: 'Gulu', description: 'Large missionary hospital with multiple specialties.', address: 'Lacor Rd, Gulu', coords: { latitude: 2.7780, longitude: 32.2960 }, imageUrl: 'https://via.placeholder.com/600x300?text=Lacor+Hospital' },
  { id: 'hosp-036', name: 'Gulu Maternity Home', district: 'Gulu', description: 'Dedicated maternity and neonatal care.', address: 'Pece-Laroo Rd, Gulu', coords: { latitude: 2.7730, longitude: 32.2890 }, imageUrl: 'https://via.placeholder.com/600x300?text=Maternity+Home' },
  { id: 'hosp-037', name: 'Faith Dental Clinic', district: 'Gulu', description: 'Dental health and oral surgery.', address: 'Atiak Rd, Gulu', coords: { latitude: 2.7760, longitude: 32.2920 }, imageUrl: 'https://via.placeholder.com/600x300?text=Dental+Clinic' },
  { id: 'hosp-038', name: 'St. Mary’s Health Centre IV', district: 'Gulu', description: 'Emergency and general outpatient care.', address: 'Gulu-Lira Rd, Gulu', coords: { latitude: 2.7700, longitude: 32.2850 }, imageUrl: 'https://via.placeholder.com/600x300?text=Health+Centre+IV' },
  { id: 'hosp-039', name: 'Gulu Skin & Allergy Clinic', district: 'Gulu', description: 'Dermatology outpatient services.', address: 'Andulo Rd, Gulu', coords: { latitude: 2.7820, longitude: 32.2870 }, imageUrl: 'https://via.placeholder.com/600x300?text=Skin+Clinic' },
  { id: 'hosp-040', name: 'Mercy Rehabilitation Centre', district: 'Gulu', description: 'Physiotherapy and occupational therapy.', address: 'Atiak Rd, Gulu', coords: { latitude: 2.7810, longitude: 32.2930 }, imageUrl: 'https://via.placeholder.com/600x300?text=Rehab+Centre' },

  // Entebbe District (10)
  { id: 'hosp-041', name: 'Entebbe General Hospital', district: 'Entebbe', description: 'Public hospital near the international airport.', address: 'Pioneer Rd, Entebbe', coords: { latitude: 0.0600, longitude: 32.4810 }, imageUrl: 'https://via.placeholder.com/600x300?text=Entebbe+Gen' },
  { id: 'hosp-042', name: 'Lake Victoria Health Centre', district: 'Entebbe', description: 'Focus on malaria, vaccinations, and tropical diseases.', address: 'Beach Rd, Entebbe', coords: { latitude: 0.0598, longitude: 32.4822 }, imageUrl: 'https://via.placeholder.com/600x300?text=Victoria+HC' },
  { id: 'hosp-043', name: 'Entebbe Women’s Clinic', district: 'Entebbe', description: 'Obstetrics, gynecology, and family planning.', address: 'Mabamba Rd, Entebbe', coords: { latitude: 0.0550, longitude: 32.4800 }, imageUrl: 'https://via.placeholder.com/600x300?text=Women+Clinic' },
  { id: 'hosp-044', name: 'Entebbe Dental Studio', district: 'Entebbe', description: 'Cosmetic dentistry and oral surgery.', address: 'Victoria Ave, Entebbe', coords: { latitude: 0.0610, longitude: 32.4830 }, imageUrl: 'https://via.placeholder.com/600x300?text=Dental+Studio' },
  { id: 'hosp-045', name: 'Entebbe Eye Care Centre', district: 'Entebbe', description: 'Full eye exams and minor surgeries.', address: 'Garden City Rd, Entebbe', coords: { latitude: 0.0620, longitude: 32.4840 }, imageUrl: 'https://via.placeholder.com/600x300?text=Eye+Care' },
  { id: 'hosp-046', name: 'Entebbe Maternity Unit', district: 'Entebbe', description: '24/7 maternity and neonatal services.', address: 'Airport Rd, Entebbe', coords: { latitude: 0.0580, longitude: 32.4805 }, imageUrl: 'https://via.placeholder.com/600x300?text=Maternity+Unit' },
  { id: 'hosp-047', name: 'Entebbe Diagnostic Labs', district: 'Entebbe', description: 'Laboratory testing and imaging.', address: 'Nakasero Rd, Entebbe', coords: { latitude: 0.0570, longitude: 32.4815 }, imageUrl: 'https://via.placeholder.com/600x300?text=Diagnostic+Labs' },
  { id: 'hosp-048', name: 'Mbamba Bay Clinic', district: 'Entebbe', description: 'General outpatient services by the bay.', address: 'Mbamba Bay, Entebbe', coords: { latitude: 0.0545, longitude: 32.4790 }, imageUrl: 'https://via.placeholder.com/600x300?text=Mbamba+Bay' },
  { id: 'hosp-049', name: 'Entebbe Skin & Allergy', district: 'Entebbe', description: 'Dermatology and allergy treatments.', address: 'Nkumba Rd, Entebbe', coords: { latitude: 0.0630, longitude: 32.4850 }, imageUrl: 'https://via.placeholder.com/600x300?text=Skin+Allergy' },
  { id: 'hosp-050', name: 'Entebbe Rehabilitation Centre', district: 'Entebbe', description: 'Physiotherapy and occupational therapy.', address: 'Lake Rd, Entebbe', coords: { latitude: 0.0605, longitude: 32.4825 }, imageUrl: 'https://via.placeholder.com/600x300?text=Rehab+Centre' },
];
